// Generated by nnc-gen -t sva: mode=both, style=monitor, depth=20, max_bound=1024
`default_nettype none

bind checker_interface checker_interface_sva checker_interface_sva_inst (
    .sys_clk(sys_clk),
    .sys_rst(sys_rst),
    .child0__y(child0__y),
    .sva_row(sva_row),
    .state_level(state_level),
    .state_mode(state_mode)
);

`default_nettype wire
