// Generated by nnc-gen -t sva: mode=both, style=monitor, depth=20, max_bound=1024
`default_nettype none

module checker_interface_sva (
    input logic sys_clk,
    input logic sys_rst,
    input logic signed [15:0] child0__y,
    input logic signed [15:0] sva_row,
    input logic signed [15:0] state_level,
    input logic signed [15:0] state_mode
);

// _VAL_0_0 = 0.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_0_0 = 16'sd0;

logic signed [15:0] sva_input_sva_row;
logic signed [15:0] sva_input_child0_a;

always_ff @(posedge sys_clk or posedge sys_rst) begin
    if (sys_rst) begin
        sva_input_sva_row <= 16'sd256;
        sva_input_child0_a <= 16'sd0;
    end else begin
        sva_input_sva_row <= sva_row;
        sva_input_child0_a <= sva_row;
    end
end

`ifndef FORMAL
logic [63:0] sva_row_2;
always_ff @(posedge sys_clk or posedge sys_rst) begin
    if (sys_rst) begin
        sva_row_2 <= 64'd0;
    end else begin
        sva_row_2 <= sva_row_2 + 64'd1;
    end
end
`endif

// observes_import (always): always sensed >= 0
logic sva_observes_import_cond;
assign sva_observes_import_cond = (child0__y >= _VAL_0_0);
logic sva_observes_import_failed_now;
assign sva_observes_import_failed_now = !sva_observes_import_cond;

`ifndef FORMAL
logic sva_observes_import_failed;
logic [63:0] sva_observes_import_reported_row;
always_ff @(posedge sys_clk or posedge sys_rst) begin
    if (sys_rst) begin
        sva_observes_import_failed <= 1'b0;
        sva_observes_import_reported_row <= 64'd0;
    end else if (sva_observes_import_failed_now && !sva_observes_import_failed) begin
        sva_observes_import_failed <= 1'b1;
        sva_observes_import_reported_row <= sva_row_2;
    end
end

task automatic sva_report(output bit failed);
    failed = 1'b0;
    if (sva_observes_import_failed) begin
        $display("SVA_RESULT observes_import fail - %0d", sva_observes_import_reported_row);
        failed = 1'b1;
    end else begin
        $display("SVA_RESULT observes_import pass - -");
    end
endtask

task automatic sva_replay_check(input logic [63:0] sva_expected_row, output bit sva_reproduced);
    sva_reproduced = (sva_observes_import_failed && sva_observes_import_reported_row == sva_expected_row);
endtask
`endif

`ifdef FORMAL
// Formal checks. The reset is active in the initial state, applied at
// the first edge and never again, so row 0 is the first edge after it.
logic sva_formal_reset = 1'b1;
always @(posedge sys_clk) sva_formal_reset <= 1'b0;
always @(*) assume (sys_rst == sva_formal_reset);
always @(posedge sys_clk) begin
    if (!(sys_rst)) begin
        sva_observes_import_check: assert (!sva_observes_import_failed_now);
    end
end
`endif

// raw sva: interface_names
always @(posedge sys_clk) begin
  assert (sva_input_sva_row == sva_input_child0_a);
  assert (child0__y <= 16'sd768);
  assert (state_level == state_level);
  assert (state_mode == 16'sd256);
end
// end raw sva: interface_names

endmodule

`default_nettype wire
