"""Contract tests for SVA stimulus encoding (input records for the RTL ports)."""

from pathlib import Path

import pytest

from nnc.cli_transform import (
    _collect_import_closure,
    _parse_verification_configs,
    _parse_verilog_configs,
)
from nnc.model.system import NncSystem
from nnc.transformers import SvaTransformer
from nnc.verification.generic_properties.native import VerificationError
from nnc.verification.sva import SvaOptions
from nnc.verification.sva_stimulus import SvaStimulus, SvaStimulusSource
from nnc.verification.sva_testbench import BenchPort, emit_testbench

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures" / "verification" / "sva"
ENCODING = FIXTURES / "stimulus" / "encoding.yaml"


def _generate(
    model: Path, source: SvaStimulusSource, options: SvaOptions | None = None
):
    cache: dict = {}
    import_paths = [str(model.parent)]
    system = NncSystem.from_yaml(
        str(model), import_paths=import_paths, _raw_data_cache=cache
    )
    transformer = SvaTransformer(
        options or SvaOptions(),
        _parse_verilog_configs(_collect_import_closure(system), cache, import_paths),
        _parse_verification_configs([system], cache),
        source,
    )
    return transformer.generate(system)


def _inputs(tmp_path: Path, text: str) -> SvaStimulusSource:
    path = tmp_path / "in.csv"
    path.write_text(text, encoding="utf-8")
    return SvaStimulusSource(inputs=path)


def test_records_are_encoded_per_port_and_decoded_back(tmp_path):
    # a: Q8.8 signed (-1.5 -> -384 = fe80); b: 4-bit logic (2.6 rounds to 3);
    # c: one bit; d: unsigned 12-bit Q4.8 (0.3 -> 77 = 04d, 3 hex digits).
    output = _generate(
        ENCODING, _inputs(tmp_path, "a,b,c,d\n-1.5,2.6,1,0.3\n0.25,15,0,15.99\n")
    )

    hex_lines = output.files["encoding_inputs.hex"].splitlines()
    assert hex_lines[0].startswith("// Generated by nnc-gen -t sva:")
    assert hex_lines[1] == (
        "// 2 records x 4 inputs: a (a_in, 16 bits), b (b, 4 bits), c (c, 1 bits), "
        "d (d, 12 bits)"
    )
    assert hex_lines[2:] == ["fe80 3 1 04d", "0040 f 0 ffd"]
    assert output.files["encoding_inputs_decoded.csv"] == (
        "a,b,c,d\n-1.5,3.0,1.0,0.30078125\n0.25,15.0,0.0,15.98828125\n"
    )


def test_testbench_drives_each_port_from_its_word(tmp_path):
    output = _generate(ENCODING, _inputs(tmp_path, "a,b,c,d\n0,0,0,0\n"))
    testbench = output.files["encoding_tb.sv"]

    assert "logic signed [15:0] a_in = 16'sd128;  // initial value" in testbench
    assert "logic [3:0] b = 4'd3;  // initial value" in testbench
    assert "logic [15:0] sva_stim [0:RECORDS*INPUTS-1];" in testbench
    assert "a_in = sva_stim[sva_k*INPUTS + 0][15:0];" in testbench
    assert "c = sva_stim[sva_k*INPUTS + 2][0:0];" in testbench
    assert "d = sva_stim[sva_k*INPUTS + 3][11:0];" in testbench


@pytest.mark.parametrize(
    ("text", "message"),
    [
        (
            "a,b,c,d\n0,0,0,0\nnan,0,0,0\n",
            r"in\.csv:3: input 'a' is not finite \(nan\)",
        ),
        ("a,b,c,d\ninf,0,0,0\n", r"in\.csv:2: input 'a' is not finite \(inf\)"),
        (
            "a,b,c,d\n128,0,0,0\n",
            r"in\.csv:2: input 'a': value 128\.0 does not fit port 'a_in' \(signed "
            r"16-bit fixed point with 8 fractional bits\)",
        ),
        # Finite, but the scaled value overflows to infinity before the range check.
        (
            "a,b,c,d\n1e308,0,0,0\n",
            r"in\.csv:2: input 'a': value 1e\+308 does not fit port 'a_in'",
        ),
        ("a,b,c,d\n0,16,0,0\n", r"input 'b': value 16\.0 does not fit port 'b'"),
        ("a,b,c,d\n0,0,0,-0.5\n", r"input 'd': value -0\.5 does not fit port 'd'"),
        ("a,b,c\n0,0,0\n", r"missing input columns: d"),
    ],
)
def test_bad_records_are_rejected_with_their_line(tmp_path, text, message):
    with pytest.raises(VerificationError, match=message):
        _generate(ENCODING, _inputs(tmp_path, text))


def test_values_outside_the_environment_range_give_one_warning_per_input(tmp_path):
    output = _generate(
        ENCODING, _inputs(tmp_path, "a,b,c,d\n0.5,0,0,0\n2,0,0,0\n-3,0,0,0\n")
    )

    assert [w for w in output.warnings if "environment" in w] == [
        f"{tmp_path / 'in.csv'}:3: input 'a' value 2.0 is outside its environment "
        "range [-1, 1]"
    ]


def test_header_without_records_gives_a_testbench_without_stimulus(tmp_path):
    output = _generate(ENCODING, _inputs(tmp_path, "a,b,c,d\n"))
    testbench = output.files["encoding_tb.sv"]

    assert "localparam int RECORDS = 0;" in testbench
    assert "$readmemh" not in testbench
    assert "sva_stim" not in testbench
    assert "for (" not in testbench
    assert "encoding_inputs.hex" not in output.files
    # The decoded inputs (header only) still drive nnc-verify --inputs.
    assert output.files["encoding_inputs_decoded.csv"] == "a,b,c,d\n"


@pytest.mark.parametrize(
    ("model", "source", "message"),
    [
        (ENCODING, SvaStimulusSource(), "a model with inputs needs --sva-inputs"),
        (
            ENCODING,
            SvaStimulusSource(steps=3),
            "--sva-steps is for models without inputs",
        ),
        (
            FIXTURES / "controller.yaml",
            SvaStimulusSource(steps=2, inputs=Path("x.csv")),
            "give only one of --sva-inputs, --sva-steps",
        ),
        (
            FIXTURES / "monitors" / "weak.yaml",
            SvaStimulusSource(inputs=Path("x.csv")),
            "--sva-inputs is for models with inputs",
        ),
        (FIXTURES / "monitors" / "weak.yaml", SvaStimulusSource(), "needs --sva-steps"),
    ],
)
def test_stimulus_source_must_fit_the_model(model, source, message):
    with pytest.raises(VerificationError, match=message):
        _generate(model, source)


def test_steps_give_a_testbench_without_stimulus_file():
    output = _generate(FIXTURES / "monitors" / "weak.yaml", SvaStimulusSource(steps=4))
    testbench = output.files["weak_tb.sv"]

    assert "localparam int RECORDS = 4;" in testbench
    assert "$readmemh" not in testbench
    assert "weak_inputs.hex" not in output.files


def test_raw_only_checker_gets_a_testbench_without_report(tmp_path):
    output = _generate(FIXTURES / "external" / "root.yaml", SvaStimulusSource(steps=2))
    # external/root.yaml has a generic property; a raw-only model has none.
    assert "sva_report" in output.files["root_tb.sv"]

    raw_only = tmp_path / "raw.yaml"
    raw_only.write_text(
        "cells:\n  - id: 1\n    contents:\n      - x = 0\n    output: [x]\n"
        "rules:\n  - x + 1 -> x\n"
        "verilog:\n  real_encoding: {kind: fixed_point, signed: true, width: 16, "
        "frac_bits: 8}\n"
        "verification:\n  backends:\n    sva:\n      raw:\n        - id: r\n"
        '          code: "// ${x}"\n',
        encoding="utf-8",
    )
    testbench = _generate(raw_only, SvaStimulusSource(steps=2)).files["raw_tb.sv"]

    assert "sva_report" not in testbench
    assert "$fatal" not in testbench


def test_testbench_names_avoid_rtl_port_names(tmp_path):
    # Ports named like the testbench's own parameters and variables.
    model = tmp_path / "names.yaml"
    model.write_text(
        "cells:\n  - id: 1\n    contents:\n      - a = 0, b = 0\n    input: [a]\n"
        "    output: [b]\nrules:\n  - a -> b\n"
        "verilog:\n  real_encoding: {kind: fixed_point, signed: true, width: 16, "
        "frac_bits: 8}\n  ports:\n"
        "    a: {direction: input, kind: fixed, width: 16, signed: true, rename: RECORDS}\n"
        "    b: {direction: output, kind: fixed, width: 16, signed: true, rename: INPUTS}\n"
        "verification:\n  properties:\n    - id: p\n      always: a >= 0\n",
        encoding="utf-8",
    )

    testbench = _generate(model, _inputs(tmp_path, "a\n1\n")).files["names_tb.sv"]

    assert "localparam int RECORDS_2 = 1;" in testbench
    assert "localparam int INPUTS_2 = 1;" in testbench
    assert "logic signed [15:0] RECORDS = 16'sd0;  // initial value" in testbench
    assert "RECORDS = sva_stim[sva_k*INPUTS_2 + 0][15:0];" in testbench


def test_active_low_reset_starts_low_and_is_released_high():
    testbench = emit_testbench(
        module="m",
        checker_module="m_sva",
        clock="clk",
        reset="rst_n",
        reset_active_high=False,
        ports=[
            BenchPort("clk", "input", 1, False),
            BenchPort("rst_n", "input", 1, False),
        ],
        checker_ports=[],
        stimulus=SvaStimulus(ports=(), initial=(), records=(), steps=2),
        hex_file="m_inputs.hex",
        has_report=True,
        header="// header",
    )

    assert "    logic rst_n = 1'b0;" in testbench
    assert "        rst_n = 1'b1;" in testbench


@pytest.mark.parametrize(
    ("child_module", "message"),
    [
        ("root_sva", "the checker module name 'root_sva' is already a module"),
        ("root_tb", "the testbench module name 'root_tb' is already a module"),
    ],
)
def test_generated_module_names_must_not_be_rtl_modules(
    tmp_path, child_module, message
):
    (tmp_path / "child.yaml").write_text(
        f"module:\n  name: {child_module}\n"
        "cells:\n  - id: 1\n    contents:\n      - a = 0, y = 0\n    input: [a]\n"
        "    output: [y]\nrules:\n  - a -> y\n"
        "verilog:\n  real_encoding: {kind: fixed_point, signed: true, width: 16, "
        "frac_bits: 8}\n",
        encoding="utf-8",
    )
    root = tmp_path / "root.yaml"
    root.write_text(
        "module:\n  name: root\n"
        "imports:\n  - module: child.yaml\n    as: c0\n    connections: {a: x}\n"
        "cells:\n  - id: 1\n    contents:\n      - x = 0\n    output: [x]\n"
        "rules:\n  - x + 1 -> x\n"
        "verilog:\n  real_encoding: {kind: fixed_point, signed: true, width: 16, "
        "frac_bits: 8}\n"
        "verification:\n  properties:\n    - id: p\n      always: x >= 0\n",
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match=message):
        _generate(root, SvaStimulusSource(steps=1))
