// Generated by nnc-gen -t sva: mode=simulation, style=monitor, depth=20, max_bound=1024
// Testbench for sva_monitors: 6 input records from monitors_inputs.hex
// (inputs in this order: u -> u_in). Run it from the output directory,
// or pass +stimulus=<path of monitors_inputs.hex>.
`timescale 1ns/1ps
`default_nettype none

module sva_monitors_tb;
    localparam int RECORDS = 6;
    localparam int INPUTS = 1;

    logic clk = 1'b0;
    logic rst = 1'b1;
    logic signed [15:0] u_in = 16'sd0;  // initial value
    logic signed [15:0] x_out;
    logic signed [15:0] count;
    logic [15:0] sva_stim [0:RECORDS*INPUTS-1];

    sva_monitors dut (
        .clk(clk),
        .rst(rst),
        .u_in(u_in),
        .x_out(x_out),
        .count(count)
    );

    sva_monitors_sva sva_checker (
        .clk(clk),
        .rst(rst),
        .state_count(dut.state_count),
        .state_x(dut.state_x),
        .u_in(dut.u_in),
        .state_mode(dut.state_mode)
    );

    always #5 clk = ~clk;

    initial begin
        bit sva_failed;
        string sva_stimulus_file;
        if (!$value$plusargs("stimulus=%s", sva_stimulus_file)) sva_stimulus_file = "monitors_inputs.hex";
        $readmemh(sva_stimulus_file, sva_stim);
        // Reset: applied at the first rising edge, released here.
        @(negedge clk);
        rst = 1'b0;
        // Record k drives the transition from row k-1 to row k.
        for (int sva_k = 0; sva_k < RECORDS; sva_k++) begin
            u_in = sva_stim[sva_k*INPUTS + 0][15:0];
            @(negedge clk);
        end
        // The last sampling edge has seen the last row.
        @(negedge clk);
        sva_checker.sva_report(sva_failed);
        if (sva_failed) $fatal(1, "SVA: a generic property failed");
        $finish;
    end
endmodule

`default_nettype wire
