// Generated by nnc-gen -t sva: mode=simulation, style=concurrent, depth=20, max_bound=1024
`default_nettype none

module sva_monitors_sva (
    input logic clk,
    input logic rst,
    input logic signed [15:0] state_count,
    input logic signed [15:0] state_x,
    input logic signed [15:0] u_in,
    input logic signed [15:0] state_mode
);

// _VAL_0_0 = 0.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_0_0 = 16'sd0;
// _VAL_0_5 = 0.5 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_0_5 = 16'sd128;
// _VAL_100_0 = 100.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_100_0 = 16'sd25600;
// _VAL_10_0 = 10.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_10_0 = 16'sd2560;
// _VAL_11_0 = 11.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_11_0 = 16'sd2816;
// _VAL_1_0 = 1.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_1_0 = 16'sd256;
// _VAL_2_0 = 2.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_2_0 = 16'sd512;
// _VAL_3_0 = 3.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_3_0 = 16'sd768;
// _VAL_4_0 = 4.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_4_0 = 16'sd1024;
// _VAL_5_0 = 5.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_5_0 = 16'sd1280;
// _VAL_7_0 = 7.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_7_0 = 16'sd1792;
// _VAL_8_0 = 8.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_8_0 = 16'sd2048;

logic signed [15:0] sva_input_u_in;

always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_input_u_in <= 16'sd0;
    end else begin
        sva_input_u_in <= u_in;
    end
end

// Row position (row 0 is the first edge after reset); saturates at 5.
logic [2:0] sva_step;
always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_step <= 3'd0;
    end else if (sva_step != 3'd5) begin
        sva_step <= sva_step + 3'd1;
    end
end

`ifndef FORMAL
logic [63:0] sva_row;
always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_row <= 64'd0;
    end else begin
        sva_row <= sva_row + 64'd1;
    end
end
`endif

// always_pass (always): always count >= 0
sva_always_pass: assert property (@(posedge clk) disable iff (rst)
    ((state_count >= _VAL_0_0)))
    else $error("SVA_FAIL always_pass row %0d", $sampled(sva_row));

// always_fail (always): always x < 4
sva_always_fail: assert property (@(posedge clk) disable iff (rst)
    ((state_x < _VAL_4_0)))
    else $error("SVA_FAIL always_fail row %0d", $sampled(sva_row));

// always_limit (always): always count <= LIMIT
sva_always_limit: assert property (@(posedge clk) disable iff (rst)
    ((state_count <= _VAL_4_0)))
    else $error("SVA_FAIL always_limit row %0d", $sampled(sva_row));

// always_scaled (always): always x * 0.5 < 4
sva_always_scaled: assert property (@(posedge clk) disable iff (rst)
    ((16'((32'(state_x) * 32'(_VAL_0_5)) >>> 8) < _VAL_4_0)))
    else $error("SVA_FAIL always_scaled row %0d", $sampled(sva_row));

// always_late (always): always x < 3, from_step 4
sva_always_late: assert property (@(posedge clk) disable iff (rst)
    (sva_step >= 3'd4) |-> ((state_x < _VAL_3_0)))
    else $error("SVA_FAIL always_late row %0d", $sampled(sva_row));

// never_input (never): never u == 3
sva_never_input: assert property (@(posedge clk) disable iff (rst)
    !((sva_input_u_in == _VAL_3_0)))
    else $error("SVA_FAIL never_input row %0d", $sampled(sva_row));

// never_late (never): never x == 3, from_step 3
sva_never_late: assert property (@(posedge clk) disable iff (rst)
    (sva_step >= 3'd3) |-> !((state_x == _VAL_3_0)))
    else $error("SVA_FAIL never_late row %0d", $sampled(sva_row));

// eventually_busy (eventually): eventually mode == ctrl.BUSY
sva_eventually_busy: assert property (@(posedge clk) disable iff (rst)
    (sva_step == 3'd0) |-> strong(##[0:$] ((state_mode == 16'sd256))))
    else $error("SVA_FAIL eventually_busy row %0d", $sampled(sva_row));

// eventually_open (eventually): eventually x > 100
sva_eventually_open: assert property (@(posedge clk) disable iff (rst)
    (sva_step == 3'd0) |-> strong(##[0:$] ((state_x > _VAL_100_0))))
    else $error("SVA_FAIL eventually_open row %0d", $sampled(sva_row));

// eventually_late (eventually): eventually x == 3, from_step 3
sva_eventually_late: assert property (@(posedge clk) disable iff (rst)
    (sva_step == 3'd0) |-> strong(##[3:$] ((state_x == _VAL_3_0))))
    else $error("SVA_FAIL eventually_late row %0d", $sampled(sva_row));

// within_pass (eventually_within): eventually count == 3
sva_within_pass: assert property (@(posedge clk) disable iff (rst)
    (sva_step == 3'd0) |-> strong(##[1:4] ((state_count == _VAL_3_0))))
    else $error("SVA_FAIL within_pass row %0d", $sampled(sva_row));

// within_zero (eventually_within): eventually x == 0
sva_within_zero: assert property (@(posedge clk) disable iff (rst)
    (sva_step == 3'd0) |-> strong(##[0:0] ((state_x == _VAL_0_0))))
    else $error("SVA_FAIL within_zero row %0d", $sampled(sva_row));

// within_fail (eventually_within): eventually x == 7
sva_within_fail: assert property (@(posedge clk) disable iff (rst)
    (sva_step == 3'd0) |-> strong(##[0:2] ((state_x == _VAL_7_0))))
    else $error("SVA_FAIL within_fail row %0d", $sampled(sva_row));

// within_late_fail (eventually_within): eventually u == 2, from_step 3
sva_within_late_fail: assert property (@(posedge clk) disable iff (rst)
    (sva_step == 3'd0) |-> strong(##[3:4] ((sva_input_u_in == _VAL_2_0))))
    else $error("SVA_FAIL within_late_fail row %0d", $sampled(sva_row));

// within_open (eventually_within): eventually x > 100
sva_within_open: assert property (@(posedge clk) disable iff (rst)
    (sva_step == 3'd0) |-> strong(##[2:50] ((state_x > _VAL_100_0))))
    else $error("SVA_FAIL within_open row %0d", $sampled(sva_row));

// cover_hit (cover): cover mode == ctrl.BUSY && x == 11
sva_cover_hit: cover property (@(posedge clk) disable iff (rst)
    (((state_mode == 16'sd256) && (state_x == _VAL_11_0))))
    $display("SVA_COVER cover_hit row %0d", $sampled(sva_row));

// cover_late_miss (cover): cover x == 1, from_step 2
sva_cover_late_miss: cover property (@(posedge clk) disable iff (rst)
    (sva_step >= 3'd2) && ((state_x == _VAL_1_0)))
    $display("SVA_COVER cover_late_miss row %0d", $sampled(sva_row));

// response_after_zero_pass (response_after): then mode == ctrl.BUSY, when u > 2
sva_response_after_zero_pass: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in > _VAL_2_0)) |-> ((state_mode == 16'sd256)))
    else $error("SVA_FAIL response_after_zero_pass row %0d", $sampled(sva_row));

// response_after_zero_fail (response_after): then u == 5, when mode == ctrl.BUSY
sva_response_after_zero_fail: assert property (@(posedge clk) disable iff (rst)
    ((state_mode == 16'sd256)) |-> ((sva_input_u_in == _VAL_5_0)))
    else $error("SVA_FAIL response_after_zero_fail row %0d", $sampled(sva_row));

// response_after_fail (response_after): then count > 3, when u > 0
sva_response_after_fail: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in > _VAL_0_0)) |-> strong(##[1:1] ((state_count > _VAL_3_0))))
    else $error("SVA_FAIL response_after_fail row %0d", $sampled(sva_row));

// response_after_late_pass (response_after): then count > 2, when u > 0, from_step 2
sva_response_after_late_pass: assert property (@(posedge clk) disable iff (rst)
    (sva_step >= 3'd2) && ((sva_input_u_in > _VAL_0_0)) |-> strong(##[1:1] ((state_count > _VAL_2_0))))
    else $error("SVA_FAIL response_after_late_pass row %0d", $sampled(sva_row));

// response_after_open (response_after): then x > 10, when u == 3
sva_response_after_open: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_3_0)) |-> strong(##[2:2] ((state_x > _VAL_10_0))))
    else $error("SVA_FAIL response_after_open row %0d", $sampled(sva_row));

// response_after_two_fail (response_after): then count == 2, when u == 1
sva_response_after_two_fail: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_1_0)) |-> strong(##[2:2] ((state_count == _VAL_2_0))))
    else $error("SVA_FAIL response_after_two_fail row %0d", $sampled(sva_row));

// response_within_exact_pass (response_within): then mode == ctrl.IDLE, when u == 2
sva_response_within_exact_pass: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_2_0)) |-> strong(##[2:2] ((state_mode == 16'sd0))))
    else $error("SVA_FAIL response_within_exact_pass row %0d", $sampled(sva_row));

// response_within_exact_fail (response_within): then x == 1, when u == 1
sva_response_within_exact_fail: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_1_0)) |-> strong(##[2:2] ((state_x == _VAL_1_0))))
    else $error("SVA_FAIL response_within_exact_fail row %0d", $sampled(sva_row));

// response_within_zero (response_within): then x == 3, when u == 2
sva_response_within_zero: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_2_0)) |-> ((state_x == _VAL_3_0)))
    else $error("SVA_FAIL response_within_zero row %0d", $sampled(sva_row));

// response_within_pass (response_within): then count >= 3, when u > 0
sva_response_within_pass: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in > _VAL_0_0)) |-> strong(##[0:3] ((state_count >= _VAL_3_0))))
    else $error("SVA_FAIL response_within_pass row %0d", $sampled(sva_row));

// response_within_fail (response_within): then x > 5, when u == 1
sva_response_within_fail: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_1_0)) |-> strong(##[0:1] ((state_x > _VAL_5_0))))
    else $error("SVA_FAIL response_within_fail row %0d", $sampled(sva_row));

// response_within_ignores_early (response_within): then x == 1, when u == 1
sva_response_within_ignores_early: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_1_0)) |-> strong(##[1:2] ((state_x == _VAL_1_0))))
    else $error("SVA_FAIL response_within_ignores_early row %0d", $sampled(sva_row));

// response_within_late_window (response_within): then mode == ctrl.BUSY, when u == 2
sva_response_within_late_window: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_2_0)) |-> strong(##[2:3] ((state_mode == 16'sd256))))
    else $error("SVA_FAIL response_within_late_window row %0d", $sampled(sva_row));

// response_within_open_overlapping (response_within): then x > 100, when u > 0
sva_response_within_open_overlapping: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in > _VAL_0_0)) |-> strong(##[1:10] ((state_x > _VAL_100_0))))
    else $error("SVA_FAIL response_within_open_overlapping row %0d", $sampled(sva_row));

// always_after_pass (persistence): then_always count >= 3, when mode == ctrl.BUSY
sva_always_after_pass: assert property (@(posedge clk) disable iff (rst)
    ((state_mode == 16'sd256)) |-> always ((state_count >= _VAL_3_0)))
    else $error("SVA_FAIL always_after_pass row %0d", $sampled(sva_row));

// always_after_fail (persistence): then_always x == 8, when u == 5
sva_always_after_fail: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in == _VAL_5_0)) |-> nexttime[1] always ((state_x == _VAL_8_0)))
    else $error("SVA_FAIL always_after_fail row %0d", $sampled(sva_row));

// always_after_zero_fail (persistence): then_always mode == ctrl.IDLE, when u > 0
sva_always_after_zero_fail: assert property (@(posedge clk) disable iff (rst)
    ((sva_input_u_in > _VAL_0_0)) |-> always ((state_mode == 16'sd0)))
    else $error("SVA_FAIL always_after_zero_fail row %0d", $sampled(sva_row));

// always_after_late_pass (persistence): then_always x > 7, when u > 0, from_step 3
sva_always_after_late_pass: assert property (@(posedge clk) disable iff (rst)
    (sva_step >= 3'd3) && ((sva_input_u_in > _VAL_0_0)) |-> always ((state_x > _VAL_7_0)))
    else $error("SVA_FAIL always_after_late_pass row %0d", $sampled(sva_row));

endmodule

`default_nettype wire
