// Generated by nnc-gen -t sva: mode=formal, style=monitor, depth=12, max_bound=1024
`default_nettype none

module formal_follow_sva (
    input logic clk,
    input logic rst,
    input logic signed [15:0] state_x,
    input logic signed [15:0] u_in
);

// _VAL_0_0 = 0.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_0_0 = 16'sd0;
// _VAL_5_0 = 5.0 in fixed-point Q8.8
localparam logic signed [15:0] _VAL_5_0 = 16'sd1280;

logic signed [15:0] sva_input_u_in;

always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_input_u_in <= 16'sd0;
    end else begin
        sva_input_u_in <= u_in;
    end
end

`ifndef FORMAL
logic [63:0] sva_row;
always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_row <= 64'd0;
    end else begin
        sva_row <= sva_row + 64'd1;
    end
end
`endif

// x_follows_input (always): always x == u
logic sva_x_follows_input_cond;
assign sva_x_follows_input_cond = (state_x == sva_input_u_in);
logic sva_x_follows_input_failed_now;
assign sva_x_follows_input_failed_now = !sva_x_follows_input_cond;

// input_in_range (always): always u >= 0 && u <= 5
logic sva_input_in_range_cond;
assign sva_input_in_range_cond = ((sva_input_u_in >= _VAL_0_0) && (sva_input_u_in <= _VAL_5_0));
logic sva_input_in_range_failed_now;
assign sva_input_in_range_failed_now = !sva_input_in_range_cond;

// x_in_range (always): always x >= 0 && x <= 5
logic sva_x_in_range_cond;
assign sva_x_in_range_cond = ((state_x >= _VAL_0_0) && (state_x <= _VAL_5_0));
logic sva_x_in_range_failed_now;
assign sva_x_in_range_failed_now = !sva_x_in_range_cond;

// input_never_max (never): never u == 5
logic sva_input_never_max_cond;
assign sva_input_never_max_cond = (sva_input_u_in == _VAL_5_0);
logic sva_input_never_max_failed_now;
assign sva_input_never_max_failed_now = sva_input_never_max_cond;

`ifndef FORMAL
logic sva_x_follows_input_failed;
logic [63:0] sva_x_follows_input_reported_row;
always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_x_follows_input_failed <= 1'b0;
        sva_x_follows_input_reported_row <= 64'd0;
    end else if (sva_x_follows_input_failed_now && !sva_x_follows_input_failed) begin
        sva_x_follows_input_failed <= 1'b1;
        sva_x_follows_input_reported_row <= sva_row;
    end
end

logic sva_input_in_range_failed;
logic [63:0] sva_input_in_range_reported_row;
always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_input_in_range_failed <= 1'b0;
        sva_input_in_range_reported_row <= 64'd0;
    end else if (sva_input_in_range_failed_now && !sva_input_in_range_failed) begin
        sva_input_in_range_failed <= 1'b1;
        sva_input_in_range_reported_row <= sva_row;
    end
end

logic sva_x_in_range_failed;
logic [63:0] sva_x_in_range_reported_row;
always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_x_in_range_failed <= 1'b0;
        sva_x_in_range_reported_row <= 64'd0;
    end else if (sva_x_in_range_failed_now && !sva_x_in_range_failed) begin
        sva_x_in_range_failed <= 1'b1;
        sva_x_in_range_reported_row <= sva_row;
    end
end

logic sva_input_never_max_failed;
logic [63:0] sva_input_never_max_reported_row;
always_ff @(posedge clk or posedge rst) begin
    if (rst) begin
        sva_input_never_max_failed <= 1'b0;
        sva_input_never_max_reported_row <= 64'd0;
    end else if (sva_input_never_max_failed_now && !sva_input_never_max_failed) begin
        sva_input_never_max_failed <= 1'b1;
        sva_input_never_max_reported_row <= sva_row;
    end
end

task automatic sva_report(output bit failed);
    failed = 1'b0;
    if (sva_x_follows_input_failed) begin
        $display("SVA_RESULT x_follows_input fail - %0d", sva_x_follows_input_reported_row);
        failed = 1'b1;
    end else begin
        $display("SVA_RESULT x_follows_input pass - -");
    end
    if (sva_input_in_range_failed) begin
        $display("SVA_RESULT input_in_range fail - %0d", sva_input_in_range_reported_row);
        failed = 1'b1;
    end else begin
        $display("SVA_RESULT input_in_range pass - -");
    end
    if (sva_x_in_range_failed) begin
        $display("SVA_RESULT x_in_range fail - %0d", sva_x_in_range_reported_row);
        failed = 1'b1;
    end else begin
        $display("SVA_RESULT x_in_range pass - -");
    end
    if (sva_input_never_max_failed) begin
        $display("SVA_RESULT input_never_max fail - %0d", sva_input_never_max_reported_row);
        failed = 1'b1;
    end else begin
        $display("SVA_RESULT input_never_max pass - -");
    end
endtask

task automatic sva_replay_check(input logic [63:0] sva_expected_row, output bit sva_reproduced);
    sva_reproduced = (sva_x_follows_input_failed && sva_x_follows_input_reported_row == sva_expected_row) || (sva_input_in_range_failed && sva_input_in_range_reported_row == sva_expected_row) || (sva_x_in_range_failed && sva_x_in_range_reported_row == sva_expected_row) || (sva_input_never_max_failed && sva_input_never_max_reported_row == sva_expected_row);
endtask
`endif

`ifdef FORMAL
// Formal checks. The reset is active in the initial state, applied at
// the first edge and never again, so row 0 is the first edge after it.
logic sva_formal_reset = 1'b1;
always @(posedge clk) sva_formal_reset <= 1'b0;
always @(*) assume (rst == sva_formal_reset);
// verification.environment.u.range on the live input
always @(*) assume (u_in >= 16'sd0 && u_in <= 16'sd1280);
always @(posedge clk) begin
    if (!(rst)) begin
        sva_x_follows_input_check: assert (!sva_x_follows_input_failed_now);
        sva_input_in_range_check: assert (!sva_input_in_range_failed_now);
        sva_x_in_range_check: assert (!sva_x_in_range_failed_now);
        sva_input_never_max_check: assert (!sva_input_never_max_failed_now);
    end
end
`endif

endmodule

`default_nettype wire
